name: vision_pro_eye_strainer
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  freezed_annotation: ^2.4.1
  hooks_riverpod: ^2.4.10
  riverpod_annotation: ^2.3.4
  very_good_analysis: ^5.1.0

dev_dependencies:
  build_runner: ^2.4.8
  custom_lint: ^0.6.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  riverpod_generator: ^2.3.11
  riverpod_lint: ^2.3.9

flutter:
  uses-material-design: true
